In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14, 4,2, 3]

[3.14, 4, 2, 3]

In [4]:
np.array([3.14, 4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1,2,3,4])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
              [4,5,6]])

In [9]:
type(a2)

numpy.ndarray

In [10]:
a2.shape

(2, 3)

In [11]:
a2.ndim


2

In [12]:
a2.dtype

dtype('int64')

In [13]:
a2.size

6

In [14]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros([2,4]).dtype

dtype('float64')

In [16]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np.ones([3,6], dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np.arange(0,20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [20]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
#Seed for reproducibility
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [22]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [23]:
np.random.normal(0, 1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [24]:
np.random.randint(0,10, (4,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [25]:
np.random.rand(4,4)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

In [26]:
#One-dimensional subarray

In [27]:
x1 = np.random.randint(20, size = 6)

In [28]:
x1

array([15, 13, 16, 17,  5,  9])

In [29]:
x1[4], x1[0], x1[-1]

(5, 15, 9)

In [30]:
#Multi-dimensional aray

In [31]:
x2 = np.random.randint(10, size = (3,4))

In [32]:
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]])

In [33]:
x2[1,2]

4

In [34]:
x2[1,2] = 6

In [35]:
x2

array([[3, 0, 5, 0],
       [1, 2, 6, 2],
       [0, 3, 2, 0]])

In [36]:
x1

array([15, 13, 16, 17,  5,  9])

In [37]:
x1[0:3]

array([15, 13, 16])

In [38]:
x1[2:4]

array([16, 17])

In [39]:
x1[::2]

array([15, 16,  5])

In [40]:
x2

array([[3, 0, 5, 0],
       [1, 2, 6, 2],
       [0, 3, 2, 0]])

In [41]:
x2[:2, :3]

array([[3, 0, 5],
       [1, 2, 6]])

In [42]:
x2[:,:2]

array([[3, 0],
       [1, 2],
       [0, 3]])

In [43]:
#Reshaping of Arrays and Transpose   
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
grid = np.arange(1,10)
grid.shape

(9,)

In [45]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
x = np.array([1,2,3])

In [47]:
x.shape

(3,)

In [48]:
x.reshape((1,3)).shape

(1, 3)

In [49]:
x = np.array([[1.,2.],[3.,4.]])

In [50]:
x

array([[1., 2.],
       [3., 4.]])

In [51]:
x.T

array([[1., 3.],
       [2., 4.]])

In [52]:
#Array Concatenation and Spliting

In [53]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [54]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [55]:
grid = np.array([[1,2,3],
               [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.concatenate((grid, grid)) #axis = 0 by default

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [58]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],
               [6,5,4]])

In [59]:
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [60]:
# horizontally stack to arrays: hstack
y = np.array([[99],
             [99]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [61]:
#splitting of arrays
x = np.array([1,2,3,99,69,3,2,1])

In [62]:
x1, x2, x3 = np.split(x, [3,5])

In [63]:
x1

array([1, 2, 3])

In [64]:
x2

array([99, 69])

In [65]:
x3

array([3, 2, 1])

In [66]:
#broadcasting and vectorized operations
a = np.arange(3)

In [67]:
a

array([0, 1, 2])

In [68]:
a+5 #broadcasting

array([5, 6, 7])

In [69]:
b = np.ones((3,3))

In [70]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
a.shape, b.shape

((3,), (3, 3))

In [72]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [73]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [74]:
c = np.arange(3).reshape((3,1)) 

In [75]:
c

array([[0],
       [1],
       [2]])

In [76]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [77]:
#manipulationg & comparing arrays
list_number = [1,2,3]

In [78]:
ll  = np.array(list_number)

In [79]:
ll

array([1, 2, 3])

In [80]:
sum(ll)

6

In [81]:
np.sum(ll)

6

In [82]:
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [83]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

612 μs ± 15.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.14 μs ± 176 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [84]:
np.mean(massive_array)

0.49644077223750666

In [85]:
np.max(massive_array)

0.9999779517807228

In [86]:
np.min(massive_array)

7.2449638492178e-05

In [87]:
#standard deviation and variance

In [88]:
dog_height = [600, 470, 170, 430, 300 ]
dog_height = np.array(dog_height)
np.var(dog_height)

21704.0

In [89]:
np.sqrt(np.var(dog_height))

147.32277488562318

In [90]:
#sorting arrays np.sort use an quicksort algorithms
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [91]:
#A related function is argsort, which instead returns the indices of the sorted elements
np.argsort(x)

array([1, 0, 3, 2, 4])

In [92]:
np.random.seed(42)
MatA = np.random.randint(0,10, size = (4,6))

In [93]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [94]:
np.sort(MatA, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [95]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [96]:
#Linear Algebra
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [97]:
B = np.array([[6,5],
              [4,3],
              [2,1]])

In [98]:
#A (3x3) dot product B (3x2)
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [99]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [100]:
#B (3x2) dot A(3x3)
B.T #(2x3) dot A(3x3)

array([[6, 4, 2],
       [5, 3, 1]])

In [101]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [102]:
#Dot Product Ex 

In [103]:
#num of jars sold
np.random.seed(0)
sales_amounts = np.random.randint(20, size = (5,3))

In [104]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [105]:
#Create weekly_sales DataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [106]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [107]:
# create a price array
prices = np.array([10,8,12])

In [108]:
butter_prices = pd.DataFrame(prices.reshape(1,3) , index = ["Price"], columns  = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [109]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [110]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [111]:
total_prices = weekly_sales.dot(butter_prices.T)

In [112]:
total_prices

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [113]:
weekly_sales["Total Price"] = total_prices
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Price
Mon               12             15              0          240
Tues               3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142